platform :ios, '12.0'

target 'TensorIOWebinarDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TensorIOWebinarDemo

  pod 'TensorIO/Core', '~> 1.2.0'
  pod 'TensorIO/TensorFlow', '~> 1.2.0'

  target 'TensorIOWebinarDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TensorIOWebinarDemoUITests' do
    # Pods for testing
  end

end
